//! `validate` — empyrean wrapper's per-channel validation runner.
//!
//! Runs the propagation / ephemeris / orbit-determination test cases
//! through [`empyrean::Context`] (the safe Rust wrapper over the C
//! ABI — same path the Python / C / CLI channels ride) and emits a
//! per-channel [`ValidationResult`] JSON tagged `channel: "rust"`.
//!
//! Channel-agnostic meta operations (merge-external, report,
//! ci-check) live in the `empyrean-validation` CLI; this binary only
//! does per-row replay.
//!
//! [`ValidationResult`]: empyrean_validation::schema::ValidationResult

use std::path::PathBuf;

use clap::{Parser, Subcommand};

use empyrean::Context;

mod runner;
mod synth;
mod walk;

#[derive(Parser, Debug)]
#[command(
    name = "validate",
    about = "Run empyrean-wrapper-channel propagation / ephemeris / OD validation against JPL Horizons."
)]
struct Cli {
    #[command(subcommand)]
    command: Command,
}

#[derive(Subcommand, Debug)]
enum Command {
    /// Run propagation + ephemeris validation against Horizons.
    Run(RunArgs),
    /// Run orbit-determination validation against MPC PSV fixtures.
    Od(OdArgs),
    /// Run the walk-forward covariance-realism family from the window
    /// manifest.
    Walk(WalkArgs),
    /// Generate the synthetic (perfect-model) fixture set for the
    /// covariance-realism family: truth fit + truth ephemeris + known noise,
    /// written as PSVs with the injected σ reported, plus the manifest.
    Synthesize(SynthesizeArgs),
}

#[derive(Parser, Debug)]
struct SynthesizeArgs {
    /// Real PSV fixtures directory (sibling `manifest.json` supplies the
    /// source snapshot id).
    #[arg(long, default_value = "../../fixtures/psv")]
    fixtures_dir: PathBuf,
    /// Output root: one lane per noise law under `<out_root>/<tag>/`
    /// (`gaussian/`, `t4/`, …), each with `psv/`, `manifest.json`,
    /// `windows.json`, `synthetic.json`.
    #[arg(short, long)]
    out_root: PathBuf,
    /// Noise laws, comma-separated: gaussian | student-t (with --nu). All
    /// laws share one truth fit + truth ephemeris per object.
    #[arg(long, value_delimiter = ',', default_values_t = ["gaussian".to_string()])]
    noise: Vec<String>,
    /// Student-t degrees of freedom (>= 3; the rows still report the
    /// Gaussian-equivalent σ).
    #[arg(long)]
    nu: Option<u32>,
    /// Global seed; every row's draw is a pure function of (seed, object,
    /// station, obsTime).
    #[arg(long, default_value_t = 1)]
    seed: u64,
    /// Injected σ (arcsec) for every station outside the VFC17 survey table.
    #[arg(long, default_value_t = empyrean_validation::synthetic::FIDUCIAL_SIGMA_ARCSEC)]
    fiducial_sigma_arcsec: f64,
    /// Force model tier for the truth fit and the truth ephemeris.
    #[arg(long, default_value = "standard")]
    tier: String,
    /// Subset of object names (empty = all). Unselected objects still get
    /// header-only PSVs so the manifest generator's invariant holds.
    #[arg(long, value_delimiter = ',')]
    only: Vec<String>,
    /// EFCC2020 debias table directory for the regenerated manifest.
    #[arg(long)]
    debias_dir: PathBuf,
    /// Empyrean data directory.
    #[arg(long)]
    data_dir: Option<PathBuf>,
    /// Worker thread count (0 = rayon default).
    #[arg(long)]
    threads: Option<usize>,
}

#[derive(Parser, Debug)]
struct WalkArgs {
    /// Window manifest path (generated by `empyrean-validation windows`).
    #[arg(long, default_value = "../../fixtures/windows.json")]
    manifest: PathBuf,
    /// Profile to run: full | ci | ladder.
    #[arg(long, default_value = "ci")]
    profile: String,
    /// JSON file with the config-arm set; omitted = the built-in
    /// {default, no-rejection, no-nightly} set.
    #[arg(long)]
    config_set: Option<PathBuf>,
    /// Subset of arm names to run (empty = all in the set).
    #[arg(long, value_delimiter = ',')]
    arms: Vec<String>,
    /// Subset of object names (empty = all eligible).
    #[arg(long, value_delimiter = ',')]
    only: Vec<String>,
    /// Output JSON path for the gate-visible thin rows; the
    /// `_windows.jsonl` / `_predictions.jsonl` sidecars are written
    /// beside it.
    #[arg(short, long, default_value = "results/validation_rust_walk.json")]
    output: PathBuf,
    /// Force model tier.
    #[arg(long, default_value = "standard")]
    tier: String,
    /// PSV fixtures directory.
    #[arg(long, default_value = "../../fixtures/psv")]
    fixtures_dir: PathBuf,
    /// Empyrean data directory.
    #[arg(long)]
    data_dir: Option<PathBuf>,
    /// Worker thread count (0 = rayon default).
    #[arg(long)]
    threads: Option<usize>,
    /// Uncertainty-transport modes for predictions: first-order |
    /// sigma-points | monte-carlo. Each mode beyond first-order adds a
    /// `<arm>+sp` / `<arm>+mc` series without refitting. (second-order
    /// and agm are engine-gated and refuse by name.)
    #[arg(long, value_delimiter = ',', default_values_t = ["first-order".to_string()])]
    uncertainty_modes: Vec<String>,
    /// Monte-Carlo draws per window for the monte-carlo mode.
    #[arg(long, default_value_t = walk::DEFAULT_MC_SAMPLES)]
    mc_samples: usize,
    /// Run the full fit-side config grid (debias × rejection × nightly =
    /// 12 arms) instead of the built-in arm set; combine with
    /// --uncertainty-modes for the prediction axis. --arms still filters.
    #[arg(long, default_value_t = false)]
    grid: bool,
    /// Override every arm's σ policy: preset (the engine default — the
    /// VFCC2017 floor) | reported (the rows' own rmsRA/rmsDec verbatim).
    /// The synthetic lane runs `reported`: its rows carry the true noise σ,
    /// and the 0.2″ fiducial sits below the preset's 1″ default floor.
    #[arg(long)]
    sigma_policy: Option<String>,
    /// Synthetic-lane provenance (`synthetic.json`): every object whose
    /// truth solved for non-gravitational parameters is fit with
    /// solve_for = state-and-nongrav in every arm (the oracle model), so
    /// the estimator's covariance can be measured with the right model
    /// separately from the auto-escalation gate.
    #[arg(long)]
    nongrav_from: Option<PathBuf>,
    /// Tag appended to every arm name (`<arm>.<tag>`), so a rerun under a
    /// different policy can be scored beside the original series.
    #[arg(long)]
    arm_tag: Option<String>,
}

#[derive(Parser, Debug)]
struct RunArgs {
    /// Output JSON path.
    #[arg(short, long, default_value = "results/validation_rust.json")]
    output: PathBuf,
    /// Subset of object names to run (empty = all).
    #[arg(long, value_delimiter = ',')]
    only: Vec<String>,
    /// Force model tiers to evaluate.
    #[arg(long, value_delimiter = ',', default_values_t = ["standard".to_string()])]
    tiers: Vec<String>,
    /// Number of timing runs per propagation.
    #[arg(long, default_value_t = 3)]
    n_timing_runs: usize,
    /// Worker thread count (0 = rayon default).
    #[arg(long)]
    threads: Option<usize>,
    /// Empyrean data directory; defaults to ~/.empyrean/data/.
    #[arg(long)]
    data_dir: Option<PathBuf>,
    /// Disk-cache directory for SBDB / Horizons queries.
    #[arg(long, default_value = "~/.empyrean/cache")]
    cache_dir: PathBuf,
    /// Skip attaching a synthetic Cartesian covariance to the input
    /// orbits. By default each test orbit carries a typical-NEO
    /// covariance (1 km position σ, 1 mm/s velocity σ) so the
    /// propagator dispatches to its Jet1 STM path — the path real users
    /// hit because empyrean is uncertainty-first by design. Setting this
    /// flag drops covariance and exercises the f64-only path for
    /// like-for-like timing comparisons against external propagators
    /// (kete, ASSIST) that don't propagate uncertainty.
    #[arg(long)]
    no_covariance: bool,
}

#[derive(Parser, Debug)]
struct OdArgs {
    /// Output JSON path.
    #[arg(short, long, default_value = "results/validation_rust_od.json")]
    output: PathBuf,
    /// Subset of object names (empty = all that have a PSV fixture).
    #[arg(long, value_delimiter = ',')]
    only: Vec<String>,
    /// Force model tier.
    #[arg(long, default_value = "standard")]
    tier: String,
    /// Max DC iterations. Default 100 matches the engine's library default
    /// so all five validation channels (rust / python / c / cli / core)
    /// use the same iteration cap.
    #[arg(long, default_value_t = 100)]
    max_iterations: u32,
    /// PSV fixtures directory.
    #[arg(long, default_value = "../../fixtures/psv")]
    fixtures_dir: PathBuf,
    /// Empyrean data directory.
    #[arg(long)]
    data_dir: Option<PathBuf>,
    /// Disk-cache directory for the SBDB orbit-comparison sidecar query.
    #[arg(long, default_value = "~/.empyrean/cache")]
    cache_dir: PathBuf,
}

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let cli = Cli::parse();
    match cli.command {
        Command::Run(args) => run(args),
        Command::Od(args) => od(args),
        Command::Walk(args) => walk_cmd(args),
        Command::Synthesize(args) => synthesize_cmd(args),
    }
}

fn synthesize_cmd(args: SynthesizeArgs) -> Result<(), Box<dyn std::error::Error>> {
    if let Some(t) = args.threads {
        rayon::ThreadPoolBuilder::new()
            .num_threads(t)
            .build_global()?;
    }
    let tier = match args.tier.as_str() {
        "approximate" => empyrean::ForceModelTier::Approximate,
        "basic" => empyrean::ForceModelTier::Basic,
        "standard" => empyrean::ForceModelTier::Standard,
        other => return Err(format!("unknown tier {other:?}").into()),
    };
    let models = args
        .noise
        .iter()
        .map(|n| empyrean_validation::synthetic::NoiseModel::parse(n, args.nu))
        .collect::<Result<Vec<_>, _>>()?;
    if !(args.fiducial_sigma_arcsec > 0.0 && args.fiducial_sigma_arcsec.is_finite()) {
        return Err(format!(
            "fiducial sigma must be positive and finite, got {}",
            args.fiducial_sigma_arcsec
        )
        .into());
    }
    eprintln!("Loading empyrean context...");
    let ctx = Context::from_data_dir(args.data_dir.as_deref())?;
    std::fs::create_dir_all(&args.out_root)?;
    synth::run(
        &ctx,
        &synth::SynthArgs {
            fixtures_dir: args.fixtures_dir,
            out_root: args.out_root,
            models,
            seed: args.seed,
            fiducial_sigma_arcsec: args.fiducial_sigma_arcsec,
            tier,
            tier_name: args.tier,
            only: args.only,
            debias_dir: args.debias_dir,
        },
    )?;
    Ok(())
}

fn walk_cmd(args: WalkArgs) -> Result<(), Box<dyn std::error::Error>> {
    if let Some(t) = args.threads {
        rayon::ThreadPoolBuilder::new()
            .num_threads(t)
            .build_global()?;
    }
    let manifest: empyrean_validation::predict_schema::WindowManifest =
        serde_json::from_str(&std::fs::read_to_string(&args.manifest)?)
            .map_err(|e| format!("parse manifest {}: {e}", args.manifest.display()))?;
    // The manifest must describe the fixtures on disk: compare its pinned
    // snapshot id against the fixture manifest's. A mismatch means the walk
    // would fit data the windowing was not derived from.
    let fixture_manifest = args
        .fixtures_dir
        .parent()
        .map(|d| d.join("manifest.json"))
        .filter(|p| p.exists());
    if let Some(fm) = fixture_manifest {
        let v: serde_json::Value = serde_json::from_str(&std::fs::read_to_string(&fm)?)?;
        if let Some(id) = v["snapshot_id"].as_str()
            && id != manifest.snapshot_id
        {
            return Err(format!(
                "window manifest snapshot {} != fixture snapshot {} — regenerate the \
                 window manifest against the fixtures on disk",
                manifest.snapshot_id, id
            )
            .into());
        }
    }
    let mut arms = match (&args.config_set, args.grid) {
        (Some(_), true) => {
            return Err("--config-set and --grid are mutually exclusive".into());
        }
        (Some(p), false) => {
            serde_json::from_str::<Vec<walk::ArmSpec>>(&std::fs::read_to_string(p)?)
                .map_err(|e| format!("parse config set {}: {e}", p.display()))?
        }
        (None, true) => walk::grid_arms(),
        (None, false) => walk::builtin_arms(),
    };
    if let Some(policy) = &args.sigma_policy {
        for arm in &mut arms {
            arm.sigma_policy = policy.clone();
        }
    }
    let nongrav_objects: Vec<String> = match &args.nongrav_from {
        None => Vec::new(),
        Some(p) => {
            let prov: empyrean_validation::synthetic::SyntheticProvenance =
                serde_json::from_str(&std::fs::read_to_string(p)?)
                    .map_err(|e| format!("parse provenance {}: {e}", p.display()))?;
            let v: Vec<String> = prov
                .objects
                .iter()
                .filter(|o| o.truth.as_ref().is_some_and(|t| t.n_solve_for > 6))
                .map(|o| o.object.clone())
                .collect();
            eprintln!(
                "walk: oracle solve-for (state-and-nongrav) for {} objects from {}: {:?}",
                v.len(),
                p.display(),
                v
            );
            v
        }
    };
    if !args.arms.is_empty() {
        arms.retain(|a| args.arms.iter().any(|n| n == &a.name));
        if arms.is_empty() {
            return Err("no arms match the --arms filter".into());
        }
    }
    if let Some(tag) = &args.arm_tag {
        for arm in &mut arms {
            arm.name = format!("{}.{tag}", arm.name);
        }
    }
    let tier = match args.tier.as_str() {
        "approximate" => empyrean::ForceModelTier::Approximate,
        "basic" => empyrean::ForceModelTier::Basic,
        _ => empyrean::ForceModelTier::Standard,
    };

    eprintln!("Loading empyrean context...");
    let ctx = Context::from_data_dir(args.data_dir.as_deref())?;
    let modes = args
        .uncertainty_modes
        .iter()
        .map(|m| walk::UncertaintyMode::parse(m))
        .collect::<Result<Vec<_>, _>>()?;
    if !modes.contains(&walk::UncertaintyMode::Linear) {
        return Err("uncertainty_modes must include `linear` (the base series)".into());
    }
    let resolved = walk::WalkArgsResolved {
        manifest: &manifest,
        profile: args.profile.clone(),
        arms,
        only: args.only.clone(),
        fixtures_dir: args.fixtures_dir.clone(),
        tier,
        modes,
        mc_samples: args.mc_samples,
        nongrav_objects,
    };
    if let Some(parent) = args.output.parent() {
        std::fs::create_dir_all(parent)?;
    }
    // Grid metadata: every emitted series name decomposed into its four
    // config axes, so downstream visualization can treat the grid as a
    // grid rather than a flat list of arm strings. Written before the walk
    // starts — it is static, and mid-run scoring needs it.
    let arm_tag_meta = args.arm_tag.clone();
    let nongrav_meta = resolved.nongrav_objects.clone();
    let (arm_tag_ref, nongrav_ref) = (&arm_tag_meta, &nongrav_meta);
    let grid_meta: Vec<serde_json::Value> = resolved
        .arms
        .iter()
        .flat_map(|arm| {
            resolved.modes.iter().map(move |mode| {
                let series = match mode.arm_suffix() {
                    None => arm.name.clone(),
                    Some(sfx) => format!("{}+{sfx}", arm.name),
                };
                serde_json::json!({
                    "series": series,
                    "uncertainty": match mode {
                        walk::UncertaintyMode::Linear => "first-order",
                        walk::UncertaintyMode::SecondOrder => "second-order",
                        walk::UncertaintyMode::SigmaPoint => "sigma-points",
                        walk::UncertaintyMode::MonteCarlo => "monte-carlo",
                    },
                    "debias": arm.debias,
                    "rejection": arm.rejection,
                    "nightly": arm.nightly,
                    "sigma_policy": arm.sigma_policy,
                    "solve_for": arm.solve_for,
                    // The oracle overrides solve_for per object at run time;
                    // record it here so the grid file never claims an
                    // ordinary auto run for a series that was not one.
                    "solve_for_override": if nongrav_ref.is_empty() {
                        serde_json::Value::Null
                    } else {
                        serde_json::json!({
                            "solve_for": "state-and-nongrav",
                            "objects": nongrav_ref,
                        })
                    },
                    "arm_tag": arm_tag_ref,
                    "nongrav_objects": nongrav_ref,
                })
            })
        })
        .collect();
    let grid_path = sidecar_path(&args.output, "_grid.json");
    std::fs::write(&grid_path, serde_json::to_string_pretty(&grid_meta)?)?;
    eprintln!(
        "Wrote {} series descriptors to {}",
        grid_meta.len(),
        grid_path.display()
    );

    let win_path = sidecar_path(&args.output, "_windows.jsonl");
    let pred_path = sidecar_path(&args.output, "_predictions.jsonl");
    let sink = walk::StreamSink::create(&win_path, &pred_path)?;
    eprintln!(
        "Streaming sidecars to {} / {} (scoreable mid-run)",
        win_path.display(),
        pred_path.display()
    );
    let (thin_rows, counts) = walk::run_walk(&ctx, &resolved, &sink)?;

    std::fs::write(&args.output, serde_json::to_string_pretty(&thin_rows)?)?;
    eprintln!(
        "\nWrote {} thin rows to {}",
        thin_rows.len(),
        args.output.display()
    );
    eprintln!(
        "Streamed {} window records to {}",
        counts.windows,
        win_path.display()
    );
    eprintln!(
        "Streamed {} predictions to {} ({} with covariance)",
        counts.predictions,
        pred_path.display(),
        counts.predictions_with_cov
    );
    Ok(())
}

fn od(args: OdArgs) -> Result<(), Box<dyn std::error::Error>> {
    eprintln!("Loading empyrean context...");
    let ctx = Context::from_data_dir(args.data_dir.as_deref())?;

    let all_objects = empyrean_validation::catalog::all_objects();
    let selected: Vec<&empyrean_validation::catalog::ValidationObject> = if args.only.is_empty() {
        all_objects
    } else {
        all_objects
            .into_iter()
            .filter(|o| args.only.iter().any(|n| n == o.name))
            .collect()
    };
    if selected.is_empty() {
        eprintln!("No matching objects.");
        return Ok(());
    }
    let tier = match args.tier.as_str() {
        "approximate" => empyrean::ForceModelTier::Approximate,
        "basic" => empyrean::ForceModelTier::Basic,
        _ => empyrean::ForceModelTier::Standard,
    };

    let sbdb_cache_dir = expand_tilde(&args.cache_dir).join("sbdb");
    std::fs::create_dir_all(&sbdb_cache_dir)?;
    let runner::OdValidationOutput {
        results,
        captured_orbits,
        orbit_comparisons,
    } = runner::run_od_validation(
        &ctx,
        &selected,
        &args.fixtures_dir,
        args.max_iterations,
        tier,
        Some(&sbdb_cache_dir),
    );

    if let Some(parent) = args.output.parent() {
        std::fs::create_dir_all(parent)?;
    }
    let json = serde_json::to_string_pretty(&results)?;
    std::fs::write(&args.output, json)?;
    eprintln!(
        "\nWrote {} OD results to {}",
        results.len(),
        args.output.display()
    );

    // Sidecar 1: per-object fitted + propagated orbit + covariance for
    // the orbit-comparison panel.
    let orbits_path = sidecar_path(&args.output, "_orbits.jsonl");
    write_jsonl(&orbits_path, &captured_orbits)?;
    eprintln!(
        "Wrote {} captured orbits to {}",
        captured_orbits.len(),
        orbits_path.display()
    );

    // Sidecar 2: bidirectional (fitted orbit vs SBDB / find_orb) Mahalanobis
    // comparisons in Keplerian element space.
    let cmp_path = sidecar_path(&args.output, "_compare.jsonl");
    write_jsonl(&cmp_path, &orbit_comparisons)?;
    eprintln!(
        "Wrote {} orbit comparisons to {}",
        orbit_comparisons.len(),
        cmp_path.display()
    );

    Ok(())
}

fn sidecar_path(main_output: &std::path::Path, suffix: &str) -> PathBuf {
    let stem = main_output
        .file_stem()
        .and_then(|s| s.to_str())
        .unwrap_or("validation");
    let parent = main_output.parent().unwrap_or(std::path::Path::new("."));
    parent.join(format!("{stem}{suffix}"))
}

fn write_jsonl<T: serde::Serialize>(
    path: &std::path::Path,
    rows: &[T],
) -> Result<(), Box<dyn std::error::Error>> {
    let mut s = String::new();
    for row in rows {
        s.push_str(&serde_json::to_string(row)?);
        s.push('\n');
    }
    std::fs::write(path, s)?;
    Ok(())
}

fn run(args: RunArgs) -> Result<(), Box<dyn std::error::Error>> {
    eprintln!("Loading empyrean context...");
    let ctx = Context::from_data_dir(args.data_dir.as_deref())?;

    let cache_dir = expand_tilde(&args.cache_dir);
    let sbdb_cache_dir = cache_dir.join("sbdb");
    let horizons_cache_dir = cache_dir.join("horizons");
    std::fs::create_dir_all(&sbdb_cache_dir)?;
    std::fs::create_dir_all(&horizons_cache_dir)?;

    let all_objects = empyrean_validation::catalog::all_objects();
    let selected: Vec<&empyrean_validation::catalog::ValidationObject> = if args.only.is_empty() {
        all_objects
    } else {
        all_objects
            .into_iter()
            .filter(|o| args.only.iter().any(|n| n == o.name))
            .collect()
    };
    if selected.is_empty() {
        eprintln!("No matching objects.");
        return Ok(());
    }

    let config = runner::ValidateConfig {
        tiers: args.tiers,
        n_timing_runs: args.n_timing_runs,
        attach_covariance: !args.no_covariance,
    };

    let results = runner::run_propagation_validation(
        &ctx,
        &selected,
        &config,
        &horizons_cache_dir,
        &sbdb_cache_dir,
        args.threads,
    );

    if let Some(parent) = args.output.parent() {
        std::fs::create_dir_all(parent)?;
    }
    let json = serde_json::to_string_pretty(&results)?;
    std::fs::write(&args.output, json)?;
    eprintln!(
        "\nWrote {} results to {}",
        results.len(),
        args.output.display()
    );
    Ok(())
}

fn expand_tilde(p: &std::path::Path) -> PathBuf {
    let s = p.to_string_lossy();
    if let Some(rest) = s.strip_prefix("~/")
        && let Some(home) = std::env::var_os("HOME")
    {
        return PathBuf::from(home).join(rest);
    }
    p.to_path_buf()
}
